<a href="https://colab.research.google.com/github/masira-syd29/Zero-to-Pandas/blob/main/Assignment_2_Numpy_array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Function 1 np.sum

In [2]:
import numpy as np

In [4]:
arr = np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
print(np.sum(arr))

55


In [8]:
print(np.sum(arr, axis=0))

[ 7  9 11 13 15]


In [9]:
print(np.sum(arr, axis=3))

AxisError: axis 3 is out of bounds for array of dimension 2

Axis three is out of bounds for an array of dimension two

Function 2- np.sqrt()


In [11]:
arr = np.array([1,4,9,16])
arr

array([ 1,  4,  9, 16])

In [12]:
print(np.sqrt(arr))

[1. 2. 3. 4.]


In [13]:
print(np.sqrt(np.array([2.25,0.25])))

[1.5 0.5]


In [14]:
print(np.sqrt(np.array([-1,-4,-9])))

[nan nan nan]


/tmp/ipython-input-1166334244.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(np.array([-1,-4,-9])))


Sqrt does not work on negative values

Function 3 - np.mean

In [16]:
arr = np.array([2,3,4,5])
print(np.mean(arr))

3.5


In [27]:
arr1 = np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
print(np.mean(arr1))

5.0


In [30]:
print(np.mean(arr1, axis=1))

[2. 5. 8.]


In [31]:
print(np.mean("hello"))

TypeError: the resolved dtypes are not compatible with add.reduce. Resolved (dtype('<U5'), dtype('<U5'), dtype('<U10'))

Cannot perform reduce with flexible type


Function 4 - np.reshape()


In [32]:
m = np.arange(12)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
print(np.reshape(m, (6,2)))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [34]:
print(np.reshape(m, (3,2,2)))

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [35]:
print(np.reshape(m, (5,2)))

ValueError: cannot reshape array of size 12 into shape (5,2)

Cannot reshape an array of size 12 into shape (5,2)

Whenever you want to arange an array into a matrix make sure the number is divisible by the matrix array

Function 5 - np.concatenate()

In [38]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])


array([[5, 6],
       [7, 8]])

In [42]:
print(np.concatenate((a,b), axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [43]:
print(np.concatenate((a,b), axis=1))

[[1 2 5 6]
 [3 4 7 8]]


In [44]:
c = np.array([1,2,3,4])
print(np.concatenate((a,c), axis=0))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)