In [ ]:
#yeild_of_apples = w1*temperature + w2*rainfall + w3*humidity

In [ ]:
w1, w2, w3 = 0.3,0.2,0.5

In [ ]:
kanto_temp = 73
kanto_rainfall=67
kanto_humidity=43

In [ ]:
kanto_yeild_apples = kanto_temp*w1+kanto_rainfall*w2+kanto_humidity*w3
kanto_yeild_apples

56.8

In [ ]:
print(f"The expected yeilf of apples in kanto region is {kanto_yeild_apples} tones per hectre")

The expected yeilf of apples in kanto region is 56.8 tones per hectre


In [ ]:
import numpy as np
kanto = np.array([73,67,43])

In [ ]:
kanto
type(kanto)

numpy.ndarray

In [ ]:
weights = np.array([w1,w2,w3])
type(weights)

numpy.ndarray

In [ ]:
weights[0]

np.float64(0.3)

In [ ]:
kanto[2]

np.int64(43)

In [ ]:
help(np.dot)

Help on _ArrayFunctionDispatcher in module numpy:

dot(...)
    dot(a, b, out=None)

    Dot product of two arrays. Specifically,

    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).

    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.

    - If either `a` or `b` is 0-D (scalar), it is equivalent to
      :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
      preferred.

    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.

    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of
      `b`::

        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

    It uses an optimized BLAS library when possible (see `numpy.linalg`).

    Parameters
    ----------
    a : array_like
        Fir

In [ ]:
np.dot(kanto,weights)

np.float64(56.8)

In [ ]:
(kanto*weights)

array([21.9, 13.4, 21.5])

In [ ]:
(kanto*weights).sum()

np.float64(56.8)

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([9,8,7])

In [ ]:
arr1*arr2
arr2.sum()

np.int64(24)

In [ ]:
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [ ]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
  result+=x1*x2
result

CPU times: user 195 ms, sys: 0 ns, total: 195 ms
Wall time: 196 ms


833332333333500000

In [ ]:
%%time
np.dot(arr1_np, arr2_np)


CPU times: user 1.58 ms, sys: 80 µs, total: 1.66 ms
Wall time: 1.66 ms


np.int64(833332333333500000)

In [ ]:
climate_data = np.array([[73,67,43],
                        [91,88,64],
                        [87,134,58],
                        [102,43,37],
                        [69,96,70]])

In [ ]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [ ]:
climate_data.shape

(5, 3)

In [ ]:
weights

array([0.3, 0.2, 0.5])

In [ ]:
weights.dtype

dtype('float64')

In [ ]:
arr3 = np.array([[[11,12,13], [13,14,15,]],
                [[15,16,17], [17,18,19.5]]])

In [ ]:
arr3.shape

(2, 2, 3)

In [ ]:
arr3.dtype

dtype('float64')

In [ ]:
climate_data.dtype

dtype('int64')

In [ ]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [ ]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [ ]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [ ]:
# import urllib.request

# urllib.request.urlretrieve(
#     'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv',
#     'climate.txt')

In [35]:
import pandas as pd

# Load the climate data
climate_df = pd.read_csv("/content/climate.txt")

# Preview the first few rows
print(climate_df.head())


   Temperature   Rainfall   Humidity
0        27.48      19.38      40.29
1        24.31       5.44      50.81
2        28.24       3.73      88.21
3        32.62       4.95      76.85
4        23.83      43.72      46.96


In [36]:
climate_data = np.genfromtxt('/content/climate.txt', delimiter=',', skip_header=1)
print(climate_data[:5])

[[27.48 19.38 40.29]
 [24.31  5.44 50.81]
 [28.24  3.73 88.21]
 [32.62  4.95 76.85]
 [23.83 43.72 46.96]]


In [37]:
climate_data

array([[ 27.48,  19.38,  40.29],
       [ 24.31,   5.44,  50.81],
       [ 28.24,   3.73,  88.21],
       ...,
       [ 21.47,  12.15,  70.3 ],
       [ 27.48,  70.09,  68.71],
       [ 28.22, 106.58,  81.8 ]])

In [38]:
climate_data.shape

(10000, 3)

In [39]:
weights = np.array([0.3,0.2,0.5])

In [40]:
yeilds = climate_data @ weights
yeilds

array([32.265, 33.786, 53.323, ..., 44.021, 56.617, 70.682])

In [41]:
yeilds.shape

(10000,)

In [42]:
yeilds = np.random.normal(loc=300, scale=50, size=10000)

In [43]:
climate_results = np.concatenate((climate_data, yeilds.reshape(10000,1)), axis=1)
# climate_results = np.concatenate((climate_data, yeilds), axis=1)

In [44]:
climate_results

array([[ 27.48      ,  19.38      ,  40.29      , 267.24546946],
       [ 24.31      ,   5.44      ,  50.81      , 269.19074528],
       [ 28.24      ,   3.73      ,  88.21      , 348.75589017],
       ...,
       [ 21.47      ,  12.15      ,  70.3       , 290.07231403],
       [ 27.48      ,  70.09      ,  68.71      , 277.82497104],
       [ 28.22      , 106.58      ,  81.8       , 340.23786935]])

In [45]:
aar = np.arange(10)
print(aar.shape,aar)

aar_col = aar.reshape(10,1)
print(aar_col)

aar_row = aar.reshape(1,10)
print(aar_row)


(10,) [0 1 2 3 4 5 6 7 8 9]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[0 1 2 3 4 5 6 7 8 9]]


In [46]:
A = np.arange(6).reshape(3,2)
B = np.arange(3).reshape(3,1)
print(A)
print(B)

C = np.concatenate((A,B), axis=1)
print(C)

[[0 1]
 [2 3]
 [4 5]]
[[0]
 [1]
 [2]]
[[0 1 0]
 [2 3 1]
 [4 5 2]]


In [47]:
X=np.ones((2,3))
Y=np.zeros((2,3))
print(X)
print(Y)

Z = np.concatenate((X,Y), axis=1)
print(Z)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


In [48]:
np.savetxt('/content/sample_data/climate_results.txt',
           climate_results,
           fmt='%.2f',
           header = 'Temperature,Rainfall,Humidity,yeild_of_apples',
           comments='')

In [49]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,1,2,3]])


In [50]:
arr3 = np.array([[11,12,13,14],
                 [15,16,17,18],
                 [19,11,12,13]])

In [51]:
arr2+arr3

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 12, 14, 16]])

In [52]:
arr2+3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [53]:
arr3-arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [55]:
arr2*arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [54]:
arr2/2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [56]:
arr2%4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]])

In [62]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,1,2,3]])

In [61]:
arr2.shape

(3, 4)

In [63]:
arr4 = np.array([4,5,6,7])
arr4.shape

(4,)

In [64]:
arr4_replicated = np.array([[4,5,6,7],
                            [4,5,6,7],
                             [4,5,6,7]])

In [65]:
arr2+arr4_replicated

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [66]:
arr5 = np.array([7,8])

In [67]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [68]:
arr5.shape

(2,)

In [69]:
arr5_replicated = np.array([[7,8],
                            [7,8],
                            [7,8]])

In [70]:
arr2+arr5_replicated

ValueError: operands could not be broadcast together with shapes (3,4) (3,2) 

In [71]:
arr1 = np.array([[1,2,3], [3,4,5]])
arr2 = np.array([[2,2,3], [1,2,5]])

In [72]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [73]:
(arr1 == arr2).dtype

dtype('bool')

In [74]:
arr1!=arr2

array([[ True, False, False],
       [ True,  True, False]])

In [75]:
arr1>=arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [77]:
arr1 < arr2

array([[ True, False, False],
       [False, False, False]])

In [78]:
(arr1 == arr2).sum()

np.int64(3)

In [79]:
arr3 = np.array([[[11,12,13,14],
                  [13,14,15,19]],

                 [[15,16,17,21],
                  [63,92,36,18]],

                 [[98,32,81,27],
                  [17,18,19.5,43]]])

In [80]:
arr3.shape

(3, 2, 4)

In [83]:
arr3[1,1]

array([63., 92., 36., 18.])

In [84]:
arr3[1,1,2]

np.float64(36.0)

In [89]:
arr3[1:,0:1]

array([[[15., 16., 17., 21.]],

       [[98., 32., 81., 27.]]])

In [90]:
arr3[1:,0:1,:2]

array([[[15., 16.]],

       [[98., 32.]]])

In [91]:
arr3[1:,1,3]

array([18., 43.])

In [92]:
arr3[1:,1,:3]

array([[63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [93]:
arr3[:,1,:3]

array([[13. , 14. , 15. ],
       [63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [94]:
arr3[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [96]:
arr3[:2,1]

array([[13., 14., 15., 19.],
       [63., 92., 36., 18.]])

In [97]:
arr3[1,3,2,1]

IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

In [99]:
arr = np.array([np.arange(i, i+6) for i in range(0,60,10)])
print(arr)


[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [100]:
arr[1]

array([10, 11, 12, 13, 14, 15])

In [103]:
arr[1:]

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [108]:
arr[1:,2]

array([12, 22, 32, 42, 52])

In [109]:
arr[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [110]:
arr[0,3:5]

array([3, 4])

In [111]:
arr[[2,2,2,4,4,4],[0,2,4,0,2,4]]

array([20, 22, 24, 40, 42, 44])

In [112]:
arr[4:6,4:6]

array([[44, 45],
       [54, 55]])

In [114]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [115]:
np.ones([2,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [116]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [118]:
np.random.randn(2,3)

array([[ 0.24577919,  0.21621296, -1.74193819],
       [-0.07145202,  0.57583373,  2.39953534]])

In [119]:
np.full([2,3],42)

array([[42, 42, 42],
       [42, 42, 42]])

In [117]:
np.random.rand(5)

array([0.76682652, 0.83957466, 0.32984973, 0.28147278, 0.38996177])

In [120]:
np.arange(10,90,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [123]:
np.arange(10,90,3).reshape(3,3,3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [127]:
np.linspace(3,27,18)

array([ 3.        ,  4.41176471,  5.82352941,  7.23529412,  8.64705882,
       10.05882353, 11.47058824, 12.88235294, 14.29411765, 15.70588235,
       17.11764706, 18.52941176, 19.94117647, 21.35294118, 22.76470588,
       24.17647059, 25.58823529, 27.        ])

100 numpy exercises


Working with OS & FILES

Python-numerical-computing with numpy exercise
1. 5 functions you didnt know
2. 2 Working examples 1 that breaks
3. Explanation of your understanding from the functions